/**
 * Web backend — pure browser implementation of Tauri commands.
 * Uses localStorage for persistence and fetch() for A2A HTTP calls.
 *
 * IMPORTANT: Return shapes must match the camelCase types from bindings.ts,
 * which are auto-generated by tauri-specta from Rust serde(rename_all = "camelCase").
 */

// ---------------------------------------------------------------------------
// Storage helpers
// ---------------------------------------------------------------------------

function load<T>(key: string, fallback: T): T {
  try {
    const raw = localStorage.getItem(`wb:${key}`);
    return raw ? JSON.parse(raw) : fallback;
  } catch {
    return fallback;
  }
}

function save<T>(key: string, data: T): void {
  localStorage.setItem(`wb:${key}`, JSON.stringify(data));
}

function uuid(): string {
  return crypto.randomUUID();
}

function nowEpoch(): number {
  return Math.floor(Date.now() / 1000);
}

// ---------------------------------------------------------------------------
// Storage types (internal, for localStorage)
// ---------------------------------------------------------------------------

interface StoredAgent {
  id: string;
  url: string;
  nickname: string | null;
  cardJson: string;
  lastFetchedAt: number;
  workspaceId: string;
}

interface StoredHistory {
  id: string;
  agentId: string;
  skillName: string;
  requestJson: string;
  responseJson: string | null;
  status: string;
  durationMs: number | null;
  createdAt: number;
}

interface StoredSavedTest {
  id: string;
  name: string;
  agentId: string;
  skillName: string;
  requestJson: string;
  createdAt: number;
}

interface StoredWorkspace {
  id: string;
  name: string;
  createdAt: number;
}

// ---------------------------------------------------------------------------
// Conversion: storage → bindings.ts shape
// ---------------------------------------------------------------------------

function toAgentRow(s: StoredAgent) {
  return {
    id: s.id,
    url: s.url,
    nickname: s.nickname,
    card: JSON.parse(s.cardJson),
    lastFetchedAt: String(s.lastFetchedAt),
    workspaceId: s.workspaceId,
  };
}

// HistoryEntry, SavedTest, WorkspaceRow are already camelCase — return as-is

// ---------------------------------------------------------------------------
// CORS proxy helper
// ---------------------------------------------------------------------------

const PROXY_PORT = 9700;

function getProxyBaseUrl(): string {
  // In cnb.run, the proxy runs on the same host but different port
  // Locally, it's just localhost:9700
  const loc = window.location;
  if (loc.hostname.includes(".cnb.run")) {
    // cnb.run pattern: <id>-<port>.cnb.run → replace port segment
    return loc.origin.replace(/-\d+\.cnb\.run/, `-${PROXY_PORT}.cnb.run`);
  }
  return `${loc.protocol}//localhost:${PROXY_PORT}`;
}

function isLocalUrl(url: string): boolean {
  try {
    const u = new URL(url);
    const host = u.hostname;
    if (host === "localhost" || host === "127.0.0.1" || host === "0.0.0.0") return true;
    // Same origin as current page
    if (u.origin === window.location.origin) return true;
    // cnb.run sibling service (same prefix, different port)
    if (host.includes(".cnb.run") && window.location.hostname.includes(".cnb.run")) return true;
    return false;
  } catch {
    return false;
  }
}

function proxyUrl(targetUrl: string): string {
  if (isLocalUrl(targetUrl)) return targetUrl;
  return `${getProxyBaseUrl()}/proxy?url=${encodeURIComponent(targetUrl)}`;
}

// ---------------------------------------------------------------------------
// Tier A — Core commands
// ---------------------------------------------------------------------------

async function fetchAgentCard(args: Record<string, unknown>) {
  const baseUrl = (args.baseUrl as string).replace(/\/+$/, "");
  const cardUrl = `${baseUrl}/.well-known/agent.json`;
  const resp = await fetch(proxyUrl(cardUrl));
  if (!resp.ok) throw { kind: "Network", message: `Failed to fetch agent card: ${resp.status}` };
  const card = await resp.json();
  card.url = card.url || baseUrl;
  return card;
}

async function handleAddAgent(args: Record<string, unknown>) {
  const baseUrl = (args.baseUrl as string).replace(/\/+$/, "");
  const nickname = (args.nickname as string | null) || null;
  const workspaceId = args.workspaceId as string;

  const card = await fetchAgentCard({ baseUrl });
  const agents = load<StoredAgent[]>("agents", []);
  const stored: StoredAgent = {
    id: uuid(),
    url: baseUrl,
    nickname: nickname || card.name || baseUrl,
    cardJson: JSON.stringify(card),
    lastFetchedAt: nowEpoch(),
    workspaceId,
  };
  agents.push(stored);
  save("agents", agents);
  return toAgentRow(stored);
}

function listAgents(args: Record<string, unknown>) {
  const workspaceId = args.workspaceId as string;
  const agents = load<StoredAgent[]>("agents", []);
  return agents.filter((a) => a.workspaceId === workspaceId).map(toAgentRow);
}

function deleteAgent(args: Record<string, unknown>) {
  const agentId = args.agentId as string;
  const agents = load<StoredAgent[]>("agents", []);
  save("agents", agents.filter((a) => a.id !== agentId));
  return null;
}

async function refreshAgent(args: Record<string, unknown>) {
  const agentId = args.agentId as string;
  const agents = load<StoredAgent[]>("agents", []);
  const idx = agents.findIndex((a) => a.id === agentId);
  if (idx === -1) throw { kind: "NotFound", message: "Agent not found" };
  const agent = agents[idx];
  const card = await fetchAgentCard({ baseUrl: agent.url });
  agent.cardJson = JSON.stringify(card);
  agent.lastFetchedAt = nowEpoch();
  save("agents", agents);
  return toAgentRow(agent);
}

function renameAgent(args: Record<string, unknown>) {
  const agentId = args.agentId as string;
  const nickname = args.nickname as string;
  const agents = load<StoredAgent[]>("agents", []);
  const agent = agents.find((a) => a.id === agentId);
  if (agent) {
    agent.nickname = nickname;
    save("agents", agents);
  }
  return null;
}

function exportAgents(args: Record<string, unknown>) {
  const workspaceId = args.workspaceId as string;
  const agents = load<StoredAgent[]>("agents", []).filter((a) => a.workspaceId === workspaceId);
  return JSON.stringify(agents.map(toAgentRow));
}

function importAgents(args: Record<string, unknown>) {
  const jsonData = args.jsonData as string;
  const workspaceId = args.workspaceId as string;
  const imported = JSON.parse(jsonData) as Array<Record<string, unknown>>;
  const agents = load<StoredAgent[]>("agents", []);
  const result: ReturnType<typeof toAgentRow>[] = [];
  for (const a of imported) {
    const card = a.card || (a.cardJson ? JSON.parse(a.cardJson as string) : {});
    const stored: StoredAgent = {
      id: uuid(),
      url: (a.url as string) || "",
      nickname: (a.nickname as string) || null,
      cardJson: typeof card === "string" ? card : JSON.stringify(card),
      lastFetchedAt: nowEpoch(),
      workspaceId,
    };
    agents.push(stored);
    result.push(toAgentRow(stored));
  }
  save("agents", agents);
  return result;
}

async function sendTask(args: Record<string, unknown>) {
  const rawUrl = (args.agentUrl as string).replace(/\/+$/, "");
  const agentUrl = proxyUrl(`${rawUrl}/a2a`);
  const rawPayload = args.payload;
  const payload = typeof rawPayload === "string" ? rawPayload : JSON.stringify(rawPayload);
  const authHeader = args.authHeader as string | undefined;
  const extraHeaders = (args.extraHeaders as Record<string, string>) || {};
  const timeoutSecs = (args.timeoutSecs as number) || 30;

  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    ...extraHeaders,
  };
  if (authHeader) {
    const [key, ...rest] = authHeader.split(": ");
    headers[key] = rest.join(": ");
  }

  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutSecs * 1000);

  try {
    const resp = await fetch(agentUrl, {
      method: "POST",
      headers,
      body: payload,
      signal: controller.signal,
    });
    if (!resp.ok) {
      const text = await resp.text().catch(() => "");
      throw { kind: "Network", message: `HTTP ${resp.status}: ${text}` };
    }
    const result = await resp.json();

    // Auto-poll for async tasks (same logic as Rust client)
    const state = result?.result?.status?.state || result?.result?.status;
    if (state === "submitted" || state === "working" || state === "pending" || state === "running") {
      return await pollTask(agentUrl, result.result.id, headers, timeoutSecs);
    }

    return result;
  } finally {
    clearTimeout(timer);
  }
}

async function pollTask(
  agentUrl: string,
  taskId: string,
  headers: Record<string, string>,
  timeoutSecs: number,
): Promise<unknown> {
  const maxPolls = Math.min(timeoutSecs * 2, 240);
  for (let i = 0; i < maxPolls; i++) {
    await new Promise((r) => setTimeout(r, 1000));
    const pollPayload = JSON.stringify({
      jsonrpc: "2.0",
      method: "tasks/get",
      params: { id: taskId },
      id: i + 2,
    });
    const resp = await fetch(agentUrl, {
      method: "POST",
      headers,
      body: pollPayload,
    });
    if (!resp.ok) continue;
    const result = await resp.json();
    const state = result?.result?.status?.state || result?.result?.status;
    if (state !== "submitted" && state !== "working" && state !== "pending" && state !== "running") {
      return result;
    }
  }
  throw { kind: "Timeout", message: "Task polling timed out" };
}

// Streaming fallback — do sync fetch, fire channel callback once
async function streamTask(args: Record<string, unknown>) {
  const agentUrl = args.agentUrl as string;
  const payload = args.payload as string;
  const authHeader = args.authHeader as string | undefined;
  const extraHeaders = (args.extraHeaders as Record<string, string>) || {};
  const onEvent = args.onEvent as unknown;

  // Channel serializes as { __CHANNEL_KEY__: id } or number
  let channelId: number | null = null;
  if (typeof onEvent === "object" && onEvent !== null && "__CHANNEL_KEY__" in (onEvent as Record<string, unknown>)) {
    channelId = (onEvent as Record<string, unknown>).__CHANNEL_KEY__ as number;
  } else if (typeof onEvent === "number") {
    channelId = onEvent;
  }

  // Do a regular send_task
  const result = await sendTask({ agentUrl, payload, authHeader, extraHeaders });
  const taskId = (result as any)?.result?.id || uuid();

  // Fire the channel callback with the result
  if (channelId !== null) {
    const callbacks = (window as any).__TAURI_INTERNALS__?.__callbacks as Map<number, Function> | undefined;
    const cb = callbacks?.get(channelId);
    if (cb) {
      cb({
        event: "task_event",
        data: {
          Done: {
            id: taskId,
            status: (result as any)?.result?.status || { state: "completed" },
            artifacts: (result as any)?.result?.artifacts || [],
            raw: result,
          },
        },
      });
    }
  }

  return taskId;
}

// ---------------------------------------------------------------------------
// History
// ---------------------------------------------------------------------------

function saveHistory(args: Record<string, unknown>) {
  const history = load<StoredHistory[]>("history", []);
  const entry: StoredHistory = {
    id: uuid(),
    agentId: args.agentId as string,
    skillName: args.skillName as string,
    requestJson: args.requestJson as string,
    responseJson: (args.responseJson as string) || null,
    status: args.status as string,
    durationMs: (args.durationMs as number) || null,
    createdAt: nowEpoch(),
  };
  history.unshift(entry);
  if (history.length > 500) history.length = 500;
  save("history", history);
  return entry.id;
}

function listHistory(args: Record<string, unknown>) {
  const agentId = args.agentId as string | undefined;
  const search = args.search as string | undefined;
  const limit = (args.limit as number) || 50;
  let history = load<StoredHistory[]>("history", []);
  if (agentId) history = history.filter((h) => h.agentId === agentId);
  if (search) {
    const q = search.toLowerCase();
    history = history.filter(
      (h) => h.skillName.toLowerCase().includes(q) || h.requestJson.toLowerCase().includes(q),
    );
  }
  return history.slice(0, limit);
}

function clearHistory(args: Record<string, unknown>) {
  const agentId = args.agentId as string | undefined;
  if (agentId) {
    const history = load<StoredHistory[]>("history", []);
    save("history", history.filter((h) => h.agentId !== agentId));
  } else {
    save("history", []);
  }
  return null;
}

// ---------------------------------------------------------------------------
// Saved Tests
// ---------------------------------------------------------------------------

function saveTest(args: Record<string, unknown>) {
  const tests = load<StoredSavedTest[]>("saved_tests", []);
  const entry: StoredSavedTest = {
    id: uuid(),
    name: args.name as string,
    agentId: args.agentId as string,
    skillName: args.skillName as string,
    requestJson: args.requestJson as string,
    createdAt: nowEpoch(),
  };
  tests.unshift(entry);
  save("saved_tests", tests);
  return entry.id;
}

function listSavedTests(args: Record<string, unknown>) {
  const agentId = args.agentId as string | undefined;
  const skillName = args.skillName as string | undefined;
  let tests = load<StoredSavedTest[]>("saved_tests", []);
  if (agentId) tests = tests.filter((t) => t.agentId === agentId);
  if (skillName) tests = tests.filter((t) => t.skillName === skillName);
  return tests;
}

function deleteSavedTest(args: Record<string, unknown>) {
  const testId = args.testId as string;
  const tests = load<StoredSavedTest[]>("saved_tests", []);
  save("saved_tests", tests.filter((t) => t.id !== testId));
  return null;
}

// ---------------------------------------------------------------------------
// Workspaces
// ---------------------------------------------------------------------------

function ensureDefaultWorkspace(): StoredWorkspace[] {
  let workspaces = load<StoredWorkspace[]>("workspaces", []);
  if (workspaces.length === 0) {
    workspaces = [{ id: "default", name: "Default", createdAt: nowEpoch() }];
    save("workspaces", workspaces);
  }
  return workspaces;
}

function listWorkspaces() {
  return ensureDefaultWorkspace();
}

function createWorkspace(args: Record<string, unknown>) {
  const workspaces = ensureDefaultWorkspace();
  const row: StoredWorkspace = {
    id: uuid(),
    name: args.name as string,
    createdAt: nowEpoch(),
  };
  workspaces.push(row);
  save("workspaces", workspaces);
  return row;
}

function deleteWorkspace(args: Record<string, unknown>) {
  const workspaceId = args.workspaceId as string;
  const workspaces = ensureDefaultWorkspace();
  save("workspaces", workspaces.filter((w) => w.id !== workspaceId));
  return null;
}

// ---------------------------------------------------------------------------
// Settings
// ---------------------------------------------------------------------------

function getSettings() {
  return load<Record<string, string>>("settings", {});
}

function saveSetting(args: Record<string, unknown>) {
  const settings = load<Record<string, string>>("settings", {});
  settings[args.key as string] = args.value as string;
  save("settings", settings);
  return null;
}

// ---------------------------------------------------------------------------
// Headers
// ---------------------------------------------------------------------------

function storeAgentHeaders(args: Record<string, unknown>) {
  const agentId = args.agentId as string;
  const headersJson = args.headersJson as string;
  localStorage.setItem(`wb:headers:${agentId}`, headersJson);
  return null;
}

function retrieveAgentHeaders(args: Record<string, unknown>) {
  const agentId = args.agentId as string;
  return localStorage.getItem(`wb:headers:${agentId}`) || null;
}

function deleteAgentHeaders(args: Record<string, unknown>) {
  const agentId = args.agentId as string;
  localStorage.removeItem(`wb:headers:${agentId}`);
  return null;
}

// ---------------------------------------------------------------------------
// Dispatcher
// ---------------------------------------------------------------------------

const TIER_C_STUB = (cmd: string) => {
  throw { kind: "NotFound", message: `${cmd} is not available in web mode` };
};

export async function handleInvoke(cmd: string, args: Record<string, unknown>): Promise<unknown> {
  switch (cmd) {
    // Agents
    case "fetch_agent_card": return fetchAgentCard(args);
    case "add_agent": return handleAddAgent(args);
    case "list_agents": return listAgents(args);
    case "delete_agent": return deleteAgent(args);
    case "refresh_agent": return refreshAgent(args);
    case "rename_agent": return renameAgent(args);
    case "export_agents": return exportAgents(args);
    case "import_agents": return importAgents(args);

    // Tasks
    case "send_task": return sendTask(args);
    case "stream_task": return streamTask(args);
    case "cancel_task": return null;

    // History
    case "save_history": return saveHistory(args);
    case "list_history": return listHistory(args);
    case "clear_history": return clearHistory(args);

    // Saved Tests
    case "save_test": return saveTest(args);
    case "list_saved_tests": return listSavedTests(args);
    case "delete_saved_test": return deleteSavedTest(args);

    // Workspaces
    case "list_workspaces": return listWorkspaces();
    case "create_workspace": return createWorkspace(args);
    case "delete_workspace": return deleteWorkspace(args);
    case "set_active_workspace": return null;

    // Settings
    case "get_settings": return getSettings();
    case "save_setting": return saveSetting(args);
    case "get_data_path": return "browser://localStorage";
    case "set_data_path": return null;

    // Headers
    case "store_agent_headers": return storeAgentHeaders(args);
    case "retrieve_agent_headers": return retrieveAgentHeaders(args);
    case "delete_agent_headers": return deleteAgentHeaders(args);

    // Tier C — stubs
    default: return TIER_C_STUB(cmd);
  }
}
