
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getSettings() : Promise<Result<JsonValue, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveSetting(key: string, value: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_setting", { key, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fetchAgentCard(baseUrl: string) : Promise<Result<AgentCard, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_agent_card", { baseUrl }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addAgent(baseUrl: string, nickname: string | null, workspaceId: string) : Promise<Result<AgentRow, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_agent", { baseUrl, nickname, workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listAgents(workspaceId: string) : Promise<Result<AgentRow[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_agents", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteAgent(agentId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_agent", { agentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async refreshAgent(agentId: string) : Promise<Result<AgentRow, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh_agent", { agentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importAgents(jsonData: string, workspaceId: string) : Promise<Result<AgentRow[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_agents", { jsonData, workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportAgents(workspaceId: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_agents", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sendTask(agentUrl: string, payload: JsonValue, authHeader: string | null, extraHeaders: Partial<{ [key in string]: string }> | null, timeoutSecs: number | null) : Promise<Result<JsonValue, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_task", { agentUrl, payload, authHeader, extraHeaders, timeoutSecs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async streamTask(agentUrl: string, payload: JsonValue, authHeader: string | null, extraHeaders: Partial<{ [key in string]: string }> | null, onEvent: TAURI_CHANNEL<TaskEvent>) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stream_task", { agentUrl, payload, authHeader, extraHeaders, onEvent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelTask(taskId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_task", { taskId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveHistory(agentId: string, skillName: string, requestJson: string, responseJson: string | null, status: string, durationMs: number | null) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_history", { agentId, skillName, requestJson, responseJson, status, durationMs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listHistory(agentId: string | null, search: string | null, limit: number | null) : Promise<Result<JsonValue, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_history", { agentId, search, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearHistory(agentId: string | null) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_history", { agentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveTest(name: string, agentId: string, skillName: string, requestJson: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_test", { name, agentId, skillName, requestJson }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSavedTests(agentId: string | null, skillName: string | null) : Promise<Result<JsonValue, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_saved_tests", { agentId, skillName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteSavedTest(testId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_saved_test", { testId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listWorkspaces() : Promise<Result<JsonValue, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_workspaces") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createWorkspace(name: string) : Promise<Result<JsonValue, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_workspace", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteWorkspace(workspaceId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_workspace", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setActiveWorkspace(workspaceId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_active_workspace", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AgentCapabilities = { streaming?: boolean | null; pushNotifications?: boolean | null; stateTransitionHistory?: boolean | null }
export type AgentCard = { name: string; description?: string | null; url: string; version: string; protocolVersion?: string | null; capabilities: AgentCapabilities; skills: AgentSkill[]; defaultInputModes?: string[]; defaultOutputModes?: string[]; provider?: AgentProvider | null; documentationUrl?: string | null; authentication?: JsonValue | null }
export type AgentProvider = { organization?: string | null; url?: string | null }
export type AgentRow = { id: string; url: string; nickname: string | null; card: AgentCard; lastFetchedAt: string; workspaceId: string }
export type AgentSkill = { id: string; name: string; description?: string | null; tags?: string[] | null; inputModes?: string[] | null; outputModes?: string[] | null; examples?: JsonValue[] | null }
export type AppError = { kind: "Database"; message: string } | { kind: "Http"; message: string } | { kind: "Io"; message: string } | { kind: "Serialization"; message: string } | { kind: "NotFound"; message: string } | { kind: "Credential"; message: string }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type TaskEvent = { id: string | null; status: TaskStatus | null; artifact: JsonValue | null; raw: JsonValue }
export type TaskStatus = { state: string; message: string | null }
export type HistoryEntry = { id: string; taskId: string; agentId: string; skillName: string; request: JsonValue; response: JsonValue | null; status: string; latencyMs: number | null; createdAt: number }

/** helper to unwrap Result<T, E> – throws on error variant */
export function unwrap<T>(result: Result<T, AppError>): T {
	if (result.status === "ok") return result.data;
	throw new Error(result.error.message);
}

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

// @ts-ignore auto-generated, may be unused
function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
