
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getSettings() : Promise<JsonValue> {
    return await TAURI_INVOKE("get_settings");
},
async saveSetting(key: string, value: string) : Promise<null> {
    return await TAURI_INVOKE("save_setting", { key, value });
},
async fetchAgentCard(baseUrl: string) : Promise<AgentCard> {
    return await TAURI_INVOKE("fetch_agent_card", { baseUrl });
},
async addAgent(baseUrl: string, nickname: string | null, workspaceId: string) : Promise<AgentRow> {
    return await TAURI_INVOKE("add_agent", { baseUrl, nickname, workspaceId });
},
async listAgents(workspaceId: string) : Promise<AgentRow[]> {
    return await TAURI_INVOKE("list_agents", { workspaceId });
},
async deleteAgent(agentId: string) : Promise<null> {
    return await TAURI_INVOKE("delete_agent", { agentId });
},
async refreshAgent(agentId: string) : Promise<AgentRow> {
    return await TAURI_INVOKE("refresh_agent", { agentId });
},
async importAgents(jsonData: string, workspaceId: string) : Promise<AgentRow[]> {
    return await TAURI_INVOKE("import_agents", { jsonData, workspaceId });
},
async exportAgents(workspaceId: string) : Promise<string> {
    return await TAURI_INVOKE("export_agents", { workspaceId });
},
async sendTask(agentUrl: string, payload: JsonValue, authHeader: string | null, extraHeaders: Partial<{ [key in string]: string }> | null, timeoutSecs: number | null) : Promise<JsonValue> {
    return await TAURI_INVOKE("send_task", { agentUrl, payload, authHeader, extraHeaders, timeoutSecs });
},
async streamTask(agentUrl: string, payload: JsonValue, authHeader: string | null, extraHeaders: Partial<{ [key in string]: string }> | null, onEvent: TAURI_CHANNEL<TaskEvent>) : Promise<string> {
    return await TAURI_INVOKE("stream_task", { agentUrl, payload, authHeader, extraHeaders, onEvent });
},
async cancelTask(taskId: string) : Promise<null> {
    return await TAURI_INVOKE("cancel_task", { taskId });
},
async saveHistory(agentId: string, skillName: string, requestJson: string, responseJson: string | null, status: string, durationMs: number | null) : Promise<string> {
    return await TAURI_INVOKE("save_history", { agentId, skillName, requestJson, responseJson, status, durationMs });
},
async listHistory(agentId: string | null, search: string | null, limit: number | null) : Promise<JsonValue> {
    return await TAURI_INVOKE("list_history", { agentId, search, limit });
},
async clearHistory(agentId: string | null) : Promise<null> {
    return await TAURI_INVOKE("clear_history", { agentId });
},
async saveTest(name: string, agentId: string, skillName: string, requestJson: string) : Promise<string> {
    return await TAURI_INVOKE("save_test", { name, agentId, skillName, requestJson });
},
async listSavedTests(agentId: string | null, skillName: string | null) : Promise<JsonValue> {
    return await TAURI_INVOKE("list_saved_tests", { agentId, skillName });
},
async deleteSavedTest(testId: string) : Promise<null> {
    return await TAURI_INVOKE("delete_saved_test", { testId });
},
async listWorkspaces() : Promise<JsonValue> {
    return await TAURI_INVOKE("list_workspaces");
},
async createWorkspace(name: string) : Promise<JsonValue> {
    return await TAURI_INVOKE("create_workspace", { name });
},
async deleteWorkspace(workspaceId: string) : Promise<null> {
    return await TAURI_INVOKE("delete_workspace", { workspaceId });
},
async setActiveWorkspace(workspaceId: string) : Promise<null> {
    return await TAURI_INVOKE("set_active_workspace", { workspaceId });
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AgentCapabilities = { streaming?: boolean | null; pushNotifications?: boolean | null; stateTransitionHistory?: boolean | null }
export type AgentCard = { name: string; description?: string | null; url: string; version: string; protocolVersion?: string | null; capabilities: AgentCapabilities; skills: AgentSkill[]; defaultInputModes?: string[]; defaultOutputModes?: string[]; provider?: AgentProvider | null; documentationUrl?: string | null; authentication?: JsonValue | null }
export type AgentProvider = { organization?: string | null; url?: string | null }
export type AgentRow = { id: string; url: string; nickname: string | null; card: AgentCard; lastFetchedAt: string; workspaceId: string }
export type AgentSkill = { id: string; name: string; description?: string | null; tags?: string[] | null; inputModes?: string[] | null; outputModes?: string[] | null; examples?: JsonValue[] | null }
export type AppError = { kind: "Database"; message: string } | { kind: "Http"; message: string } | { kind: "Io"; message: string } | { kind: "Serialization"; message: string } | { kind: "NotFound"; message: string } | { kind: "Credential"; message: string }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type TaskEvent = { id: string | null; status: TaskStatus | null; artifact: JsonValue | null; raw: JsonValue }
export type TaskStatus = { state: string; message: string | null }

/** Application-level types (not generated by specta) **/

export type HistoryEntry = {
  id: string;
  taskId: string;
  agentId: string;
  request: JsonValue;
  response: JsonValue | null;
  status: string;
  latencyMs: number | null;
  createdAt: number;
}

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
