// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta).
// Do not edit this file manually.

/** user-defined commands **/

import { invoke as TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

// Type definitions matching Rust types (camelCase via serde rename_all)

export type AgentCapabilities = {
  streaming: boolean | null;
  pushNotifications: boolean | null;
  stateTransitionHistory: boolean | null;
};

export type AgentProvider = {
  organization: string | null;
  url: string | null;
};

export type AgentSkill = {
  id: string;
  name: string;
  description: string | null;
  tags: string[] | null;
  inputModes: string[] | null;
  outputModes: string[] | null;
  examples: unknown[] | null;
};

export type AgentCard = {
  name: string;
  description: string | null;
  url: string;
  version: string;
  protocolVersion: string | null;
  capabilities: AgentCapabilities;
  skills: AgentSkill[];
  defaultInputModes: string[];
  defaultOutputModes: string[];
  provider: AgentProvider | null;
  documentationUrl: string | null;
};

export type AgentRow = {
  id: string;
  url: string;
  nickname: string | null;
  card: AgentCard;
  lastFetchedAt: number;
  workspaceId: string;
};

export type AppError =
  | { kind: "Database"; message: string }
  | { kind: "Http"; message: string }
  | { kind: "Io"; message: string }
  | { kind: "Serialization"; message: string }
  | { kind: "NotFound"; message: string }
  | { kind: "Credential"; message: string };

export type TaskEvent = {
  id: string | null;
  status: { state: string; message: string | null } | null;
  artifact: unknown | null;
  raw: unknown;
};

export type HistoryEntry = {
  id: string;
  agentId: string;
  taskId: string;
  request: unknown;
  response: unknown;
  status: string;
  latencyMs: number | null;
  createdAt: number;
};

export type SavedTest = {
  id: string;
  name: string;
  agentId: string;
  skillId: string;
  payload: unknown;
  createdAt: number;
};

export type Workspace = {
  id: string;
  name: string;
  createdAt: number;
};

export const commands = {
  async getSettings(): Promise<Record<string, unknown>> {
    return await TAURI_INVOKE("get_settings");
  },
  async saveSettings(key: string, value: string): Promise<void> {
    await TAURI_INVOKE("save_settings", { key, value });
  },
  async fetchAgentCard(baseUrl: string): Promise<AgentCard> {
    return await TAURI_INVOKE("fetch_agent_card", { baseUrl });
  },
  async addAgent(
    baseUrl: string,
    nickname: string | null,
    workspaceId: string
  ): Promise<AgentRow> {
    return await TAURI_INVOKE("add_agent", { baseUrl, nickname, workspaceId });
  },
  async listAgents(workspaceId: string): Promise<AgentRow[]> {
    return await TAURI_INVOKE("list_agents", { workspaceId });
  },
  async deleteAgent(agentId: string): Promise<void> {
    await TAURI_INVOKE("delete_agent", { agentId });
  },
  async refreshAgent(agentId: string): Promise<AgentRow> {
    return await TAURI_INVOKE("refresh_agent", { agentId });
  },
  async importAgents(
    jsonData: string,
    workspaceId: string
  ): Promise<AgentRow[]> {
    return await TAURI_INVOKE("import_agents", { jsonData, workspaceId });
  },
  async exportAgents(workspaceId: string): Promise<string> {
    return await TAURI_INVOKE("export_agents", { workspaceId });
  },
  async sendTask(
    agentUrl: string,
    payload: unknown,
    authHeader: string | null,
    extraHeaders: Record<string, string> | null,
  ): Promise<unknown> {
    return await TAURI_INVOKE("send_task", { agentUrl, payload, authHeader, extraHeaders });
  },
  async streamTask(
    agentUrl: string,
    payload: unknown,
    authHeader: string | null,
    extraHeaders: Record<string, string> | null,
    onEvent: Channel<TaskEvent>,
  ): Promise<string> {
    return await TAURI_INVOKE("stream_task", {
      agentUrl,
      payload,
      authHeader,
      extraHeaders,
      onEvent,
    });
  },
  async cancelTask(taskId: string): Promise<void> {
    await TAURI_INVOKE("cancel_task", { taskId });
  },
  async saveHistory(
    agentId: string,
    taskId: string,
    request: unknown,
    response: unknown,
    status: string,
    latencyMs: number | null,
  ): Promise<void> {
    await TAURI_INVOKE("save_history", {
      agentId,
      taskId,
      request,
      response,
      status,
      latencyMs,
    });
  },
  async listHistory(agentId: string): Promise<HistoryEntry[]> {
    return await TAURI_INVOKE("list_history", { agentId });
  },
  async clearHistory(agentId: string): Promise<void> {
    await TAURI_INVOKE("clear_history", { agentId });
  },
  async saveTest(
    name: string,
    agentId: string,
    skillId: string,
    payload: unknown,
  ): Promise<void> {
    await TAURI_INVOKE("save_test", { name, agentId, skillId, payload });
  },
  async listSavedTests(agentId: string): Promise<SavedTest[]> {
    return await TAURI_INVOKE("list_saved_tests", { agentId });
  },
  async deleteSavedTest(testId: string): Promise<void> {
    await TAURI_INVOKE("delete_saved_test", { testId });
  },
  async listWorkspaces(): Promise<Workspace[]> {
    return await TAURI_INVOKE("list_workspaces");
  },
  async createWorkspace(name: string): Promise<Workspace> {
    return await TAURI_INVOKE("create_workspace", { name });
  },
  async deleteWorkspace(workspaceId: string): Promise<void> {
    await TAURI_INVOKE("delete_workspace", { workspaceId });
  },
  async setActiveWorkspace(workspaceId: string): Promise<void> {
    await TAURI_INVOKE("set_active_workspace", { workspaceId });
  },
};
